server.port=${PORT:3000}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-seconds=${JWT_EXPIRATION_SECONDS}
app.jwt.cookie-name=${JWT_COOKIE_NAME}
app.jwt.cookie-secure=${JWT_COOKIE_SECURE}
